CREATE DATABASE IF NOT EXISTS inspection DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE inspection;

DROP TABLE IF EXISTS operation_log;
DROP TABLE IF EXISTS task_history;
DROP TABLE IF EXISTS statistics_report;
DROP TABLE IF EXISTS warning_history;
DROP TABLE IF EXISTS warning_record;
DROP TABLE IF EXISTS inspection_record;
DROP TABLE IF EXISTS satellite_earth_station_records;
DROP TABLE IF EXISTS space_station_records;
DROP TABLE IF EXISTS ground_station_records;
DROP TABLE IF EXISTS satellite_network_records;
DROP TABLE IF EXISTS satellite_frequency_records;
DROP TABLE IF EXISTS ground_frequency_records;
DROP TABLE IF EXISTS inspection_task;
DROP TABLE IF EXISTS frequency_usage;
DROP TABLE IF EXISTS inspection_standard;
DROP TABLE IF EXISTS regulation_clause;
DROP TABLE IF EXISTS regulation;
DROP TABLE IF EXISTS radio_station;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS user_institution;
DROP TABLE IF EXISTS institution;

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户主键ID',
  username VARCHAR(64) NOT NULL COMMENT '登录用户名（唯一）',
  password VARCHAR(255) NOT NULL COMMENT '登录密码（加密存储）',
  real_name VARCHAR(64) COMMENT '用户真实姓名',
  role VARCHAR(32) NOT NULL COMMENT '角色编码（ADMIN/OPERATOR/INSPECTOR）',
  enabled TINYINT(1) DEFAULT 1 COMMENT '是否启用：1启用，0禁用',
  created_at DATETIME COMMENT '创建时间',
  updated_at DATETIME COMMENT '最后更新时间',
  UNIQUE KEY uk_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';

CREATE TABLE IF NOT EXISTS radio_station (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '台站主键ID',
  station_id BIGINT UNIQUE NOT NULL COMMENT '台站业务ID（外部系统关联键）',
  name VARCHAR(128) NOT NULL COMMENT '台站名称',
  category VARCHAR(64) COMMENT '台站类别（如一类/二类）',
  station_class VARCHAR(32) COMMENT '台站等级分类',
  station_type VARCHAR(128) COMMENT '台站类型（广播电台/微波站等）',
  service_type VARCHAR(64) COMMENT '业务类型（应急通信/公众移动通信等）',
  station_code VARCHAR(64) COMMENT '台站编码',
  address VARCHAR(255) COMMENT '台站地址',
  longitude DOUBLE COMMENT '经度',
  latitude DOUBLE COMMENT '纬度',
  license_no VARCHAR(64) COMMENT '无线电台执照号',
  valid_until DATE COMMENT '执照有效期截止日期',
  transmit_power DECIMAL(8,2) COMMENT '发射功率（dBm）',
  occupied_bandwidth DECIMAL(10,2) COMMENT '占用带宽（kHz）',
  antenna_gain DECIMAL(6,2) COMMENT '天线增益（dBi）',
  antenna_height DECIMAL(6,2) COMMENT '天线距地高度（m）',
  antenna_size DECIMAL(6,2) COMMENT '天线尺寸（m）',
  polarization VARCHAR(32) COMMENT '极化方式（水平/垂直/圆极化等）',
  max_eirp DECIMAL(8,2) COMMENT '最大等效全向辐射功率（dBm）',
  orbital_position VARCHAR(64) COMMENT '轨道位置/参数',
  total_bandwidth DECIMAL(10,2) COMMENT '总带宽（kHz）',
  review_status VARCHAR(32) DEFAULT '待审核' COMMENT '审核状态（待审核/已审核）',
  reviewed_by VARCHAR(64) COMMENT '审核人账号',
  reviewed_at DATETIME COMMENT '审核时间',
  created_at DATETIME COMMENT '创建时间',
  updated_at DATETIME COMMENT '最后更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='无线电台站主数据表';

CREATE TABLE IF NOT EXISTS frequency_usage (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '频率使用主键ID',
  station_id BIGINT COMMENT '关联台站ID（逻辑关联radio_station.station_id）',
  license_no VARCHAR(64) COMMENT '频率使用许可编号',
  frequency_range VARCHAR(128) COMMENT '频率范围（如3.4GHz-3.6GHz）',
  usage_region VARCHAR(255) COMMENT '使用地域范围',
  business_usage VARCHAR(128) COMMENT '业务用途',
  usage_deadline DATE COMMENT '使用期限截止日期',
  usage_rate DECIMAL(6,2) COMMENT '频率使用率（百分比，检查后回填）',
  eirp_spectral_density DECIMAL(8,2) COMMENT 'EIRP谱密度（dBm）',
  antenna_size DECIMAL(6,2) COMMENT '主站天线尺寸（m）',
  annual_report_submitted TINYINT(1) DEFAULT 1 COMMENT '是否已报送年度报告：1是，0否',
  spectrum_fee_paid TINYINT(1) DEFAULT 1 COMMENT '是否已缴纳频率占用费：1是，0否',
  interference_flag TINYINT(1) DEFAULT 0 COMMENT '是否存在干扰异常：1是，0否',
  technical_scheme VARCHAR(255) COMMENT '技术方案说明',
  service_personnel VARCHAR(128) COMMENT '保障/运维人员信息',
  review_status VARCHAR(32) DEFAULT '待审核' COMMENT '审核状态（待审核/已审核）',
  evidence_urls VARCHAR(2048) COMMENT '证据附件URL列表',
  created_at DATETIME COMMENT '创建时间',
  updated_at DATETIME COMMENT '最后更新时间',
  INDEX idx_frequency_station_id (station_id),
  INDEX idx_frequency_license_no (license_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='频率使用主数据表';

CREATE TABLE IF NOT EXISTS inspection_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '任务主键ID',
  task_name VARCHAR(128) NOT NULL COMMENT '任务名称',
  task_type VARCHAR(32) NOT NULL COMMENT '任务类型（台站检查任务/频率检查任务）',
  check_category VARCHAR(32) DEFAULT '地面频率使用' COMMENT '检查对象细分类（地面频率/卫星频率/卫星通信网/地面台站/空间电台/卫星地球站）',
  inspection_mode VARCHAR(32) NOT NULL COMMENT '检查类型（日常检查/重点检查）',
  trigger_source VARCHAR(64) COMMENT '触发来源（上级交办/监测发现/群众举报等）',
  station_id BIGINT COMMENT '关联台站ID（逻辑关联radio_station.station_id）',
  station_ids JSON COMMENT '关联台站ID列表（多站任务）',
  status VARCHAR(32) NOT NULL COMMENT '任务状态（待审核/进行中/已完成/已取消）',
  inspector VARCHAR(64) COMMENT '责任人员/执行人账号（PC下发给APP执行）',
  due_date DATE COMMENT '任务截止日期',
  reminded_at DATETIME COMMENT '最近一次催办时间',
  cancel_reason VARCHAR(255) COMMENT '任务撤销原因',
  description VARCHAR(512) COMMENT '任务说明',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  INDEX idx_task_type_mode (task_type, inspection_mode),
  INDEX idx_task_status (status),
  INDEX idx_task_station (station_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查任务统筹表（PC创建并下发APP执行）';

CREATE TABLE IF NOT EXISTS warning_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '预警主键ID',
  rule_name VARCHAR(128) COMMENT '触发预警的规则名称',
  level VARCHAR(16) COMMENT '预警等级（高/中/低）',
  message VARCHAR(255) COMMENT '预警消息内容',
  status VARCHAR(32) DEFAULT '未处理' COMMENT '处置状态（未处理/处理中/已处理）',
  related_task_id BIGINT COMMENT '关联任务ID（逻辑关联inspection_task.id）',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  INDEX idx_warning_related_task (related_task_id),
  INDEX idx_warning_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='违规预警记录表';

CREATE TABLE IF NOT EXISTS ground_frequency_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  task_id BIGINT NOT NULL COMMENT '关联任务ID',
  station_id BIGINT COMMENT '关联台站ID（逻辑关联radio_station.station_id）',
  inspector_name VARCHAR(64) NOT NULL COMMENT '执行检查人员',
  is_qualified TINYINT(1) COMMENT '总体是否合格：1是，0否',
  no_qualified_reason VARCHAR(255) COMMENT '不合格原因',
  check_1_1_1_1 TEXT COMMENT '附件一地面频率检查项1.1.1.1结果说明',
  check_1_1_1_2 TEXT COMMENT '附件一地面频率检查项1.1.1.2结果说明',
  check_1_1_1_3 TEXT COMMENT '附件一地面频率检查项1.1.1.3结果说明',
  check_1_1_1_4 TEXT COMMENT '附件一地面频率检查项1.1.1.4结果说明',
  check_1_1_1_5 TEXT COMMENT '附件一地面频率检查项1.1.1.5结果说明',
  check_1_1_1_6_1 TEXT COMMENT '附件一地面频率检查项1.1.1.6.1结果说明',
  check_1_1_1_6_2 TEXT COMMENT '附件一地面频率检查项1.1.1.6.2结果说明',
  check_1_1_1_6_3 TEXT COMMENT '附件一地面频率检查项1.1.1.6.3结果说明',
  check_1_1_2 TEXT COMMENT '附件一地面频率检查项1.1.2结果说明',
  check_1_1_3 TEXT COMMENT '附件一地面频率检查项1.1.3结果说明',
  check_1_1_4 TEXT COMMENT '附件一地面频率检查项1.1.4结果说明',
  check_1_1_5 TEXT COMMENT '附件一地面频率检查项1.1.5结果说明',
  check_1_1_6 TEXT COMMENT '附件一地面频率检查项1.1.6结果说明',
  check_1_1_7 TEXT COMMENT '附件一地面频率检查项1.1.7结果说明',
  check_1_1_8 TEXT COMMENT '附件一地面频率检查项1.1.8结果说明',
  check_1_1_9 TEXT COMMENT '附件一地面频率检查项1.1.9结果说明',
  check_1_1_1_1_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.1.1判定',
  check_1_1_1_2_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.1.2判定',
  check_1_1_1_3_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.1.3判定',
  check_1_1_1_4_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.1.4判定',
  check_1_1_1_5_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.1.5判定',
  check_1_1_1_6_1_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.1.6.1判定',
  check_1_1_1_6_2_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.1.6.2判定',
  check_1_1_1_6_3_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.1.6.3判定',
  check_1_1_2_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.2判定',
  check_1_1_3_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.3判定',
  check_1_1_4_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.4判定',
  check_1_1_5_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.5判定',
  check_1_1_6_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.6判定',
  check_1_1_7_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.7判定',
  check_1_1_8_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.8判定',
  check_1_1_9_result VARCHAR(16) COMMENT '附件一地面频率检查项1.1.9判定',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_ground_frequency_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='地面频率使用检查记录表';

CREATE TABLE IF NOT EXISTS satellite_frequency_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  task_id BIGINT NOT NULL COMMENT '关联任务ID',
  station_id BIGINT COMMENT '关联台站ID（逻辑关联radio_station.station_id）',
  inspector_name VARCHAR(64) NOT NULL COMMENT '执行检查人员',
  is_qualified TINYINT(1) COMMENT '总体是否合格：1是，0否',
  no_qualified_reason VARCHAR(255) COMMENT '不合格原因',
  check_1_2_1_1 TEXT COMMENT '附件一卫星频率检查项1.2.1.1结果说明',
  check_1_2_1_2 TEXT COMMENT '附件一卫星频率检查项1.2.1.2结果说明',
  check_1_2_1_3 TEXT COMMENT '附件一卫星频率检查项1.2.1.3结果说明',
  check_1_2_1_4 TEXT COMMENT '附件一卫星频率检查项1.2.1.4结果说明',
  check_1_2_1_5 TEXT COMMENT '附件一卫星频率检查项1.2.1.5结果说明',
  check_1_2_1_6_1 TEXT COMMENT '附件一卫星频率检查项1.2.1.6.1结果说明',
  check_1_2_1_6_2 TEXT COMMENT '附件一卫星频率检查项1.2.1.6.2结果说明',
  check_1_2_1_6_3 TEXT COMMENT '附件一卫星频率检查项1.2.1.6.3结果说明',
  check_1_2_1_6_4 TEXT COMMENT '附件一卫星频率检查项1.2.1.6.4结果说明',
  check_1_2_1_6_5 TEXT COMMENT '附件一卫星频率检查项1.2.1.6.5结果说明',
  check_1_2_2 TEXT COMMENT '附件一卫星频率检查项1.2.2结果说明',
  check_1_2_3 TEXT COMMENT '附件一卫星频率检查项1.2.3结果说明',
  check_1_2_4 TEXT COMMENT '附件一卫星频率检查项1.2.4结果说明',
  check_1_2_5 TEXT COMMENT '附件一卫星频率检查项1.2.5结果说明',
  check_1_2_6 TEXT COMMENT '附件一卫星频率检查项1.2.6结果说明',
  check_1_2_7 TEXT COMMENT '附件一卫星频率检查项1.2.7结果说明',
  check_1_2_8 TEXT COMMENT '附件一卫星频率检查项1.2.8结果说明',
  check_1_2_9 TEXT COMMENT '附件一卫星频率检查项1.2.9结果说明',
  check_1_2_1_1_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.1.1判定',
  check_1_2_1_2_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.1.2判定',
  check_1_2_1_3_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.1.3判定',
  check_1_2_1_4_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.1.4判定',
  check_1_2_1_5_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.1.5判定',
  check_1_2_1_6_1_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.1.6.1判定',
  check_1_2_1_6_2_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.1.6.2判定',
  check_1_2_1_6_3_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.1.6.3判定',
  check_1_2_1_6_4_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.1.6.4判定',
  check_1_2_1_6_5_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.1.6.5判定',
  check_1_2_2_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.2判定',
  check_1_2_3_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.3判定',
  check_1_2_4_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.4判定',
  check_1_2_5_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.5判定',
  check_1_2_6_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.6判定',
  check_1_2_7_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.7判定',
  check_1_2_8_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.8判定',
  check_1_2_9_result VARCHAR(16) COMMENT '附件一卫星频率检查项1.2.9判定',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_sat_frequency_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='卫星频率使用检查记录表';

CREATE TABLE IF NOT EXISTS satellite_network_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  task_id BIGINT NOT NULL COMMENT '关联任务ID',
  station_id BIGINT COMMENT '关联台站ID（逻辑关联radio_station.station_id）',
  inspector_name VARCHAR(64) NOT NULL COMMENT '执行检查人员',
  is_qualified TINYINT(1) COMMENT '总体是否合格：1是，0否',
  no_qualified_reason VARCHAR(255) COMMENT '不合格原因',
  check_1_3_1_1 TEXT COMMENT '附件一卫星通信网频率检查项1.3.1.1结果说明',
  check_1_3_1_2 TEXT COMMENT '附件一卫星通信网频率检查项1.3.1.2结果说明',
  check_1_3_1_3 TEXT COMMENT '附件一卫星通信网频率检查项1.3.1.3结果说明',
  check_1_3_1_4 TEXT COMMENT '附件一卫星通信网频率检查项1.3.1.4结果说明',
  check_1_3_1_5 TEXT COMMENT '附件一卫星通信网频率检查项1.3.1.5结果说明',
  check_1_3_1_6_1 TEXT COMMENT '附件一卫星通信网频率检查项1.3.1.6.1结果说明',
  check_1_3_1_6_2 TEXT COMMENT '附件一卫星通信网频率检查项1.3.1.6.2结果说明',
  check_1_3_1_6_3 TEXT COMMENT '附件一卫星通信网频率检查项1.3.1.6.3结果说明',
  check_1_3_1_6_4 TEXT COMMENT '附件一卫星通信网频率检查项1.3.1.6.4结果说明',
  check_1_3_1_6_5 TEXT COMMENT '附件一卫星通信网频率检查项1.3.1.6.5结果说明',
  check_1_3_2 TEXT COMMENT '附件一卫星通信网频率检查项1.3.2结果说明',
  check_1_3_3 TEXT COMMENT '附件一卫星通信网频率检查项1.3.3结果说明',
  check_1_3_4 TEXT COMMENT '附件一卫星通信网频率检查项1.3.4结果说明',
  check_1_3_5 TEXT COMMENT '附件一卫星通信网频率检查项1.3.5结果说明',
  check_1_3_6 TEXT COMMENT '附件一卫星通信网频率检查项1.3.6结果说明',
  check_1_3_7 TEXT COMMENT '附件一卫星通信网频率检查项1.3.7结果说明',
  check_1_3_8 TEXT COMMENT '附件一卫星通信网频率检查项1.3.8结果说明',
  check_1_3_9 TEXT COMMENT '附件一卫星通信网频率检查项1.3.9结果说明',
  check_1_3_1_1_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.1.1判定',
  check_1_3_1_2_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.1.2判定',
  check_1_3_1_3_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.1.3判定',
  check_1_3_1_4_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.1.4判定',
  check_1_3_1_5_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.1.5判定',
  check_1_3_1_6_1_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.1.6.1判定',
  check_1_3_1_6_2_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.1.6.2判定',
  check_1_3_1_6_3_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.1.6.3判定',
  check_1_3_1_6_4_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.1.6.4判定',
  check_1_3_1_6_5_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.1.6.5判定',
  check_1_3_2_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.2判定',
  check_1_3_3_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.3判定',
  check_1_3_4_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.4判定',
  check_1_3_5_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.5判定',
  check_1_3_6_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.6判定',
  check_1_3_7_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.7判定',
  check_1_3_8_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.8判定',
  check_1_3_9_result VARCHAR(16) COMMENT '附件一卫星通信网频率检查项1.3.9判定',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_sat_network_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='卫星通信网频率使用检查记录表';

CREATE TABLE IF NOT EXISTS ground_station_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  task_id BIGINT NOT NULL COMMENT '关联任务ID',
  station_id BIGINT COMMENT '关联台站ID（逻辑关联radio_station.station_id）',
  inspector_name VARCHAR(64) NOT NULL COMMENT '执行检查人员',
  is_qualified TINYINT(1) COMMENT '总体是否合格：1是，0否',
  no_qualified_reason VARCHAR(255) COMMENT '不合格原因',
  check_2_1_1_1 TEXT COMMENT '附件二地面台站检查项2.1.1.1结果说明',
  check_2_1_1_2_1 TEXT COMMENT '附件二地面台站检查项2.1.1.2.1结果说明',
  check_2_1_1_2_2 TEXT COMMENT '附件二地面台站检查项2.1.1.2.2结果说明',
  check_2_1_1_2_3 TEXT COMMENT '附件二地面台站检查项2.1.1.2.3结果说明',
  check_2_1_1_3_1 TEXT COMMENT '附件二地面台站检查项2.1.1.3.1结果说明',
  check_2_1_1_3_2 TEXT COMMENT '附件二地面台站检查项2.1.1.3.2结果说明',
  check_2_1_1_3_3 TEXT COMMENT '附件二地面台站检查项2.1.1.3.3结果说明',
  check_2_1_1_3_4 TEXT COMMENT '附件二地面台站检查项2.1.1.3.4结果说明',
  check_2_1_1_4_1 TEXT COMMENT '附件二地面台站检查项2.1.1.4.1结果说明',
  check_2_1_1_4_2 TEXT COMMENT '附件二地面台站检查项2.1.1.4.2结果说明',
  check_2_1_1_4_3 TEXT COMMENT '附件二地面台站检查项2.1.1.4.3结果说明',
  check_2_1_1_4_4 TEXT COMMENT '附件二地面台站检查项2.1.1.4.4结果说明',
  check_2_1_1_5_1 TEXT COMMENT '附件二地面台站检查项2.1.1.5.1结果说明',
  check_2_1_1_5_2 TEXT COMMENT '附件二地面台站检查项2.1.1.5.2结果说明',
  check_2_1_1_5_3 TEXT COMMENT '附件二地面台站检查项2.1.1.5.3结果说明',
  check_2_1_1_5_4 TEXT COMMENT '附件二地面台站检查项2.1.1.5.4结果说明',
  check_2_1_1_5_5 TEXT COMMENT '附件二地面台站检查项2.1.1.5.5结果说明',
  check_2_1_2 TEXT COMMENT '附件二地面台站检查项2.1.2结果说明',
  check_2_1_3 TEXT COMMENT '附件二地面台站检查项2.1.3结果说明',
  check_2_1_4 TEXT COMMENT '附件二地面台站检查项2.1.4结果说明',
  check_2_1_5 TEXT COMMENT '附件二地面台站检查项2.1.5结果说明',
  check_2_1_6 TEXT COMMENT '附件二地面台站检查项2.1.6结果说明',
  check_2_1_7 TEXT COMMENT '附件二地面台站检查项2.1.7结果说明',
  check_2_1_8 TEXT COMMENT '附件二地面台站检查项2.1.8结果说明',
  check_2_1_9 TEXT COMMENT '附件二地面台站检查项2.1.9结果说明',
  check_2_1_10 TEXT COMMENT '附件二地面台站检查项2.1.10结果说明',
  check_2_1_1_1_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.1判定',
  check_2_1_1_2_1_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.2.1判定',
  check_2_1_1_2_2_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.2.2判定',
  check_2_1_1_2_3_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.2.3判定',
  check_2_1_1_3_1_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.3.1判定',
  check_2_1_1_3_2_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.3.2判定',
  check_2_1_1_3_3_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.3.3判定',
  check_2_1_1_3_4_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.3.4判定',
  check_2_1_1_4_1_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.4.1判定',
  check_2_1_1_4_2_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.4.2判定',
  check_2_1_1_4_3_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.4.3判定',
  check_2_1_1_4_4_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.4.4判定',
  check_2_1_1_5_1_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.5.1判定',
  check_2_1_1_5_2_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.5.2判定',
  check_2_1_1_5_3_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.5.3判定',
  check_2_1_1_5_4_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.5.4判定',
  check_2_1_1_5_5_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.1.5.5判定',
  check_2_1_2_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.2判定',
  check_2_1_3_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.3判定',
  check_2_1_4_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.4判定',
  check_2_1_5_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.5判定',
  check_2_1_6_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.6判定',
  check_2_1_7_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.7判定',
  check_2_1_8_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.8判定',
  check_2_1_9_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.9判定',
  check_2_1_10_result VARCHAR(16) COMMENT '附件二地面台站检查项2.1.10判定',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_ground_station_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='地面台站检查记录表';

CREATE TABLE IF NOT EXISTS space_station_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  task_id BIGINT NOT NULL COMMENT '关联任务ID',
  station_id BIGINT COMMENT '关联台站ID（逻辑关联radio_station.station_id）',
  inspector_name VARCHAR(64) NOT NULL COMMENT '执行检查人员',
  is_qualified TINYINT(1) COMMENT '总体是否合格：1是，0否',
  no_qualified_reason VARCHAR(255) COMMENT '不合格原因',
  check_2_2_1_1 TEXT COMMENT '附件二空间电台检查项2.2.1.1结果说明',
  check_2_2_1_2_1 TEXT COMMENT '附件二空间电台检查项2.2.1.2.1结果说明',
  check_2_2_1_2_2 TEXT COMMENT '附件二空间电台检查项2.2.1.2.2结果说明',
  check_2_2_1_2_3 TEXT COMMENT '附件二空间电台检查项2.2.1.2.3结果说明',
  check_2_2_1_3_1 TEXT COMMENT '附件二空间电台检查项2.2.1.3.1结果说明',
  check_2_2_1_3_2 TEXT COMMENT '附件二空间电台检查项2.2.1.3.2结果说明',
  check_2_2_1_3_3 TEXT COMMENT '附件二空间电台检查项2.2.1.3.3结果说明',
  check_2_2_1_3_4 TEXT COMMENT '附件二空间电台检查项2.2.1.3.4结果说明',
  check_2_2_1_4_1 TEXT COMMENT '附件二空间电台检查项2.2.1.4.1结果说明',
  check_2_2_1_4_2 TEXT COMMENT '附件二空间电台检查项2.2.1.4.2结果说明',
  check_2_2_1_4_3 TEXT COMMENT '附件二空间电台检查项2.2.1.4.3结果说明',
  check_2_2_1_4_4 TEXT COMMENT '附件二空间电台检查项2.2.1.4.4结果说明',
  check_2_2_2 TEXT COMMENT '附件二空间电台检查项2.2.2结果说明',
  check_2_2_3 TEXT COMMENT '附件二空间电台检查项2.2.3结果说明',
  check_2_2_4 TEXT COMMENT '附件二空间电台检查项2.2.4结果说明',
  check_2_2_5 TEXT COMMENT '附件二空间电台检查项2.2.5结果说明',
  check_2_2_6 TEXT COMMENT '附件二空间电台检查项2.2.6结果说明',
  check_2_2_7 TEXT COMMENT '附件二空间电台检查项2.2.7结果说明',
  check_2_2_1_1_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.1判定',
  check_2_2_1_2_1_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.2.1判定',
  check_2_2_1_2_2_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.2.2判定',
  check_2_2_1_2_3_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.2.3判定',
  check_2_2_1_3_1_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.3.1判定',
  check_2_2_1_3_2_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.3.2判定',
  check_2_2_1_3_3_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.3.3判定',
  check_2_2_1_3_4_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.3.4判定',
  check_2_2_1_4_1_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.4.1判定',
  check_2_2_1_4_2_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.4.2判定',
  check_2_2_1_4_3_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.4.3判定',
  check_2_2_1_4_4_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.1.4.4判定',
  check_2_2_2_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.2判定',
  check_2_2_3_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.3判定',
  check_2_2_4_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.4判定',
  check_2_2_5_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.5判定',
  check_2_2_6_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.6判定',
  check_2_2_7_result VARCHAR(16) COMMENT '附件二空间电台检查项2.2.7判定',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_space_station_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='空间电台检查记录表';

CREATE TABLE IF NOT EXISTS satellite_earth_station_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  task_id BIGINT NOT NULL COMMENT '关联任务ID',
  station_id BIGINT COMMENT '关联台站ID（逻辑关联radio_station.station_id）',
  inspector_name VARCHAR(64) NOT NULL COMMENT '执行检查人员',
  is_qualified TINYINT(1) COMMENT '总体是否合格：1是，0否',
  no_qualified_reason VARCHAR(255) COMMENT '不合格原因',
  check_2_3_1_1 TEXT COMMENT '附件二卫星地球站检查项2.3.1.1结果说明',
  check_2_3_1_2_1 TEXT COMMENT '附件二卫星地球站检查项2.3.1.2.1结果说明',
  check_2_3_1_2_2 TEXT COMMENT '附件二卫星地球站检查项2.3.1.2.2结果说明',
  check_2_3_1_2_3 TEXT COMMENT '附件二卫星地球站检查项2.3.1.2.3结果说明',
  check_2_3_1_2_4 TEXT COMMENT '附件二卫星地球站检查项2.3.1.2.4结果说明',
  check_2_3_1_2_5 TEXT COMMENT '附件二卫星地球站检查项2.3.1.2.5结果说明',
  check_2_3_1_2_6 TEXT COMMENT '附件二卫星地球站检查项2.3.1.2.6结果说明',
  check_2_3_1_2_7 TEXT COMMENT '附件二卫星地球站检查项2.3.1.2.7结果说明',
  check_2_3_1_2_8 TEXT COMMENT '附件二卫星地球站检查项2.3.1.2.8结果说明',
  check_2_3_1_3_1 TEXT COMMENT '附件二卫星地球站检查项2.3.1.3.1结果说明',
  check_2_3_1_3_2 TEXT COMMENT '附件二卫星地球站检查项2.3.1.3.2结果说明',
  check_2_3_1_3_3 TEXT COMMENT '附件二卫星地球站检查项2.3.1.3.3结果说明',
  check_2_3_1_3_4 TEXT COMMENT '附件二卫星地球站检查项2.3.1.3.4结果说明',
  check_2_3_1_3_5 TEXT COMMENT '附件二卫星地球站检查项2.3.1.3.5结果说明',
  check_2_3_1_4_1 TEXT COMMENT '附件二卫星地球站检查项2.3.1.4.1结果说明',
  check_2_3_1_4_2 TEXT COMMENT '附件二卫星地球站检查项2.3.1.4.2结果说明',
  check_2_3_1_4_3 TEXT COMMENT '附件二卫星地球站检查项2.3.1.4.3结果说明',
  check_2_3_1_4_4 TEXT COMMENT '附件二卫星地球站检查项2.3.1.4.4结果说明',
  check_2_3_1_4_5 TEXT COMMENT '附件二卫星地球站检查项2.3.1.4.5结果说明',
  check_2_3_2 TEXT COMMENT '附件二卫星地球站检查项2.3.2结果说明',
  check_2_3_3 TEXT COMMENT '附件二卫星地球站检查项2.3.3结果说明',
  check_2_3_4 TEXT COMMENT '附件二卫星地球站检查项2.3.4结果说明',
  check_2_3_5 TEXT COMMENT '附件二卫星地球站检查项2.3.5结果说明',
  check_2_3_6 TEXT COMMENT '附件二卫星地球站检查项2.3.6结果说明',
  check_2_3_7 TEXT COMMENT '附件二卫星地球站检查项2.3.7结果说明',
  check_2_3_8 TEXT COMMENT '附件二卫星地球站检查项2.3.8结果说明',
  check_2_3_1_1_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.1判定',
  check_2_3_1_2_1_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.2.1判定',
  check_2_3_1_2_2_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.2.2判定',
  check_2_3_1_2_3_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.2.3判定',
  check_2_3_1_2_4_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.2.4判定',
  check_2_3_1_2_5_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.2.5判定',
  check_2_3_1_2_6_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.2.6判定',
  check_2_3_1_2_7_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.2.7判定',
  check_2_3_1_2_8_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.2.8判定',
  check_2_3_1_3_1_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.3.1判定',
  check_2_3_1_3_2_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.3.2判定',
  check_2_3_1_3_3_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.3.3判定',
  check_2_3_1_3_4_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.3.4判定',
  check_2_3_1_3_5_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.3.5判定',
  check_2_3_1_4_1_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.4.1判定',
  check_2_3_1_4_2_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.4.2判定',
  check_2_3_1_4_3_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.4.3判定',
  check_2_3_1_4_4_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.4.4判定',
  check_2_3_1_4_5_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.1.4.5判定',
  check_2_3_2_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.2判定',
  check_2_3_3_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.3判定',
  check_2_3_4_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.4判定',
  check_2_3_5_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.5判定',
  check_2_3_6_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.6判定',
  check_2_3_7_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.7判定',
  check_2_3_8_result VARCHAR(16) COMMENT '附件二卫星地球站检查项2.3.8判定',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_sat_earth_station_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='卫星地球站检查记录表';

CREATE TABLE IF NOT EXISTS warning_history (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '历史记录主键ID',
  warning_id BIGINT NOT NULL COMMENT '关联预警记录ID',
  rule_name VARCHAR(128) COMMENT '触发预警的规则名称（快照）',
  level VARCHAR(16) COMMENT '预警等级快照',
  message VARCHAR(255) COMMENT '预警消息内容快照',
  status VARCHAR(32) COMMENT '处置状态快照',
  related_task_id BIGINT COMMENT '关联任务ID',
  created_at DATETIME COMMENT '记录时间',
  updated_at DATETIME COMMENT '最后更新时间',
  INDEX idx_wh_warning (warning_id),
  INDEX idx_wh_task (related_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预警变更历史快照表';

CREATE TABLE IF NOT EXISTS inspection_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '检查记录主键ID',
  task_id BIGINT COMMENT '关联任务ID（逻辑关联inspection_task.id）',
  station_id BIGINT COMMENT '关联台站ID（逻辑关联radio_station.station_id）',
  object_type VARCHAR(64) COMMENT '检查对象类型（无线电频率/在用无线电台站）',
  item_code VARCHAR(32) COMMENT '检查项编码（如F-01/S-01）',
  item_name VARCHAR(255) COMMENT '检查项名称',
  check_type VARCHAR(64) COMMENT '检查类型（监测/书面检查/现场核查等）',
  check_method VARCHAR(255) COMMENT '检查方法说明',
  legal_basis VARCHAR(255) COMMENT '适用法律法规依据',
  inspection_mode VARCHAR(32) COMMENT '检查方式（日常/重点）',
  trigger_source VARCHAR(64) COMMENT '触发来源（交办/举报/监测发现等）',
  station_category VARCHAR(64) COMMENT '台站类别（一类/二类等）',
  result VARCHAR(32) COMMENT '检查结果（合格/不合格）',
  needs_rectification TINYINT(1) DEFAULT 0 COMMENT '是否需要整改：1是，0否',
  rectification_deadline DATE COMMENT '整改截止日期',
  annual_report_submitted TINYINT(1) DEFAULT 1 COMMENT '是否已报送年度报告：1是，0否',
  spectrum_fee_paid TINYINT(1) DEFAULT 1 COMMENT '是否已缴纳频率占用费：1是，0否',
  technical_personnel_ok TINYINT(1) DEFAULT 1 COMMENT '技术人员配置是否达标：1是，0否',
  harmful_interference TINYINT(1) DEFAULT 0 COMMENT '是否存在有害干扰：1是，0否',
  increased_frequency_required TINYINT(1) DEFAULT 0 COMMENT '是否需增配频率：1是，0否',
  process_record VARCHAR(1024) COMMENT '检查过程记录',
  evidence_urls VARCHAR(2048) COMMENT '检查证据附件URL列表',
  audit_status VARCHAR(32) DEFAULT '待审核' COMMENT '审核状态（待审核/已审核/驳回）',
  remarks VARCHAR(512) COMMENT '检查备注',
  inspector VARCHAR(64) COMMENT '检查执行人账号',
  checked_at DATETIME COMMENT '实际检查时间',
  inspection_round INT NOT NULL DEFAULT 1 COMMENT '检查轮次，首次检查=1，每次复检递增',
  created_at DATETIME COMMENT '创建时间',
  updated_at DATETIME COMMENT '最后更新时间',
  INDEX idx_record_task (task_id),
  INDEX idx_record_station (station_id),
  INDEX idx_record_audit (audit_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查记录总表（APP提交，PC审核）';

CREATE TABLE IF NOT EXISTS regulation (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '法规主键ID',
  title VARCHAR(255) NOT NULL COMMENT '法规标题',
  category VARCHAR(64) COMMENT '法规类别（行政法规/部门规章等）',
  version VARCHAR(64) COMMENT '法规版本信息',
  file_url VARCHAR(255) COMMENT '法规文件链接',
  issued_at DATE COMMENT '发布日期',
  created_at DATETIME COMMENT '创建时间',
  updated_at DATETIME COMMENT '最后更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='法规主表';

CREATE TABLE IF NOT EXISTS regulation_clause (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '条款主键ID',
  regulation_id BIGINT COMMENT '所属法规ID（逻辑关联regulation.id）',
  chapter_title VARCHAR(255) COMMENT '章节标题',
  article_no VARCHAR(64) COMMENT '条款编号',
  clause_category VARCHAR(64) COMMENT '条款分类（如频率许可/缴费义务）',
  keyword_tag VARCHAR(128) COMMENT '关键词标签（逗号分隔）',
  content TEXT COMMENT '条款内容',
  updated_at DATETIME COMMENT '最后更新时间',
  created_at DATETIME COMMENT '创建时间',
  INDEX idx_clause_regulation_id (regulation_id),
  INDEX idx_clause_category (clause_category),
  INDEX idx_clause_keyword (keyword_tag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='法规条款表';

CREATE TABLE IF NOT EXISTS inspection_standard (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '检查标准主键ID',
  object_type VARCHAR(64) COMMENT '对象类型（无线电频率/在用无线电台站）',
  station_type VARCHAR(128) COMMENT '适用台站类型',
  item_code VARCHAR(64) COMMENT '检查项编码',
  item_name VARCHAR(255) COMMENT '检查项名称',
  legal_clause VARCHAR(128) COMMENT '对应法条编号',
  check_type VARCHAR(128) COMMENT '检查类型（监测/现场核查等）',
  check_method VARCHAR(512) COMMENT '检查方法说明',
  judgment_rule VARCHAR(512) COMMENT '判定规则说明',
  severity_level VARCHAR(32) COMMENT '问题严重等级（高/中/低）',
  enabled TINYINT(1) DEFAULT 1 COMMENT '是否启用：1启用，0停用',
  updated_at DATETIME COMMENT '最后更新时间',
  created_at DATETIME COMMENT '创建时间',
  INDEX idx_standard_object (object_type),
  INDEX idx_standard_item_code (item_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查标准知识库表';

CREATE TABLE IF NOT EXISTS statistics_report (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '报表主键ID',
  name VARCHAR(128) NOT NULL COMMENT '报表名称',
  report_type VARCHAR(64) COMMENT '报表类型（时间周期/任务执行/区域统计等）',
  generated_at DATETIME COMMENT '报表生成时间',
  summary VARCHAR(512) COMMENT '报表摘要',
  data_snapshot TEXT COMMENT '统计数据快照（JSON格式）',
  created_at DATETIME COMMENT '创建时间',
  updated_at DATETIME COMMENT '最后更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统计报表表';

CREATE TABLE IF NOT EXISTS operation_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '操作日志主键ID',
  module_name VARCHAR(64) COMMENT '业务模块名称',
  operation_type VARCHAR(32) COMMENT '操作类型（新增/修改/删除/审核等）',
  target_id BIGINT COMMENT '操作目标ID（对应业务数据主键）',
  description VARCHAR(512) COMMENT '操作说明',
  operator VARCHAR(64) COMMENT '操作人账号',
  operator_role VARCHAR(32) COMMENT '操作人角色',
  operation_time DATETIME COMMENT '业务操作时间',
  created_at DATETIME COMMENT '创建时间',
  updated_at DATETIME COMMENT '最后更新时间',
  INDEX idx_operation_time (operation_time),
  INDEX idx_operation_type (operation_type),
  INDEX idx_module_name (module_name),
  INDEX idx_operator (operator)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';

CREATE TABLE IF NOT EXISTS task_history (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '任务历史记录主键ID',
  task_id BIGINT NOT NULL COMMENT '关联任务ID',
  action_type VARCHAR(32) NOT NULL COMMENT '操作类型',
  description VARCHAR(512) COMMENT '操作描述',
  operator VARCHAR(64) COMMENT '操作人账号',
  operator_role VARCHAR(32) COMMENT '操作人角色',
  created_at DATETIME COMMENT '创建时间',
  updated_at DATETIME COMMENT '最后更新时间',
  INDEX idx_task_history_task_id (task_id),
  INDEX idx_task_history_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务操作历史记录表';

CREATE TABLE IF NOT EXISTS institution (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '机构主键ID',
  name VARCHAR(128) NOT NULL COMMENT '机构名称',
  province VARCHAR(32) NOT NULL COMMENT '所属省份',
  city VARCHAR(64) NOT NULL COMMENT '所属地市',
  created_at DATETIME COMMENT '创建时间',
  updated_at DATETIME COMMENT '最后更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查机构表（全国地级市/州/盟）';

CREATE TABLE IF NOT EXISTS user_institution (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '关联主键ID',
  user_id BIGINT NOT NULL COMMENT '用户ID（逻辑关联sys_user.id）',
  institution_id BIGINT NOT NULL COMMENT '机构ID（逻辑关联institution.id）',
  created_at DATETIME COMMENT '创建时间',
  updated_at DATETIME COMMENT '最后更新时间',
  UNIQUE KEY uk_user_institution (user_id, institution_id),
  INDEX idx_ui_institution (institution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户机构关联表';
